baseURL = 'https://inclerepo.github.io/'
locale = 'ko-KR'
timeZone = 'Asia/Seoul'
defaultContentLanguage = 'ko'
title = 'Dev Archive'
theme = 'PaperMod'
copyright = '© 2026 [인클](https://github.com/IncleRepo)'

enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  env = 'production'
  author = '인클'
  description = '백엔드 개발 과정에서 공부한 내용을 기록합니다.'
  defaultTheme = 'auto'
  disableThemeToggle = false
  ShowLastMod = true
  ShowToc = true
  TocOpen = false
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false

  [params.homeInfoParams]
    Title = 'Dev Archive'
    Content = '백엔드 개발 과정에서 공부한 내용을 기록합니다.'

  [params.assets]
    favicon = '/favicon-v2.ico'
    favicon16x16 = '/favicon-v2-16x16.png'
    favicon32x32 = '/favicon-v2-32x32.png'
    apple_touch_icon = '/apple-touch-icon-v2.png'

[[menu.main]]
  identifier = 'posts'
  name = '글'
  url = '/posts/'
  weight = 10

[[menu.main]]
  identifier = 'categories'
  name = '카테고리'
  url = '/categories/'
  weight = 20

[[menu.main]]
  identifier = 'tags'
  name = '태그'
  url = '/tags/'
  weight = 30

[[menu.main]]
  identifier = 'about'
  name = '소개'
  url = '/about/'
  weight = 40
